# Basic
title: Mr.Mao
#subtitle: 
description: ä¸€ä¸ªäººè‡³å°‘æ‹¥æœ‰ä¸€ä¸ªæ¢¦æƒ³ï¼Œæœ‰ä¸€ä¸ªç†ç”±å»åšå¼ºã€‚å¿ƒè‹¥æ²¡æœ‰æ –æ¯çš„åœ°æ–¹ï¼Œåˆ°å“ªé‡Œéƒ½æ˜¯åœ¨æµæµªã€‚
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: æ°¸å‡¡
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: æŒç»­é›†æˆ / è‡ªåŠ¨åŒ–
url: "http://lilian.info"

# Comment
comment:
    # disqus: lilian
    duoshuo: leopard 

# Social
social:
    #weibo: 2344041987
    github: maoyongfan2
    #gsite: liliandreamworld
    csdn: maoyongfan3
    # twitter: 
    mail: 850447881@qq.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: 7c428daff2760d60102aec565a5c731b
    

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-97614726-1   
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/dearLilian/dearLilian.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /blog/:year/:month/:title.html 

markdown: kramdown


kramdown:
  input:  GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true
  extensions:
    - autolink
    - footnotes
    - smart
  syntax_highlighter: rouge


# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ–‡ç« , description: archive, url: '/archive'}   
    - {title: åˆ†ç±», description: tags, url: '/tags'}
    - {title: ç•™è¨€, description: messages, url: '/messages'}
    #- {title: èµ„æº, description: links, url: '/links'}      
    - {title: å…³äº, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"